In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('AUCs.txt', header=0, sep='\t')

In [3]:
data

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0            adult (sample)  0.763   0.768    0.771      0.798
1             breast cancer  0.599   0.591    0.590      0.569
2   breast cancer wisconsin  0.954   0.971    0.968      0.967
3                       cmc  0.628   0.661    0.654      0.657
4                ionosphere  0.882   0.888    0.886      0.898
5                      iris  0.936   0.931    0.916      0.931
6           liver disorders  0.661   0.668    0.609      0.685
7               lung cancer  0.583   0.583    0.563      0.625
8              lymphography  0.775   0.838    0.866      0.875
9                  mushroom  1.000   1.000    1.000      1.000
10            primary tumor  0.940   0.962    0.965      0.962
11                    rheum  0.619   0.666    0.614      0.669
12                   voting  0.972   0.981    0.975      0.975
13                     wine  0.957   0.978    0.946      0.970

In [4]:
from scipy import stats

In [15]:
anses = []

for x in list(data.drop('Unnamed: 0', axis=1).columns):
    for y in list(data.drop('Unnamed: 0', axis=1).columns):
        if x == y:
            continue
        print("{}, {}: {}".format(x, y, stats.wilcoxon(data[x], data[y])))
        anses.append((x, y, stats.wilcoxon(data[x], data[y])[1]))

C4.5, C4.5+m: WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963)
C4.5, C4.5+cf: WilcoxonResult(statistic=43.0, pvalue=0.861262330095348)
C4.5, C4.5+m+cf: WilcoxonResult(statistic=11.0, pvalue=0.015906444101703374)
C4.5+m, C4.5: WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963)
C4.5+m, C4.5+cf: WilcoxonResult(statistic=17.0, pvalue=0.046332729793395394)
C4.5+m, C4.5+m+cf: WilcoxonResult(statistic=22.0, pvalue=0.3278256758446406)
C4.5+cf, C4.5: WilcoxonResult(statistic=43.0, pvalue=0.861262330095348)
C4.5+cf, C4.5+m: WilcoxonResult(statistic=17.0, pvalue=0.046332729793395394)
C4.5+cf, C4.5+m+cf: WilcoxonResult(statistic=10.0, pvalue=0.022909099354356588)
C4.5+m+cf, C4.5: WilcoxonResult(statistic=11.0, pvalue=0.015906444101703374)
C4.5+m+cf, C4.5+m: WilcoxonResult(statistic=22.0, pvalue=0.3278256758446406)
C4.5+m+cf, C4.5+cf: WilcoxonResult(statistic=10.0, pvalue=0.022909099354356588)


In [12]:
stats.wilcoxon(data['C4.5'], data['C4.5+m'])

WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963)

In [17]:
sorted(anses, key=lambda x: x[2])

[('C4.5', 'C4.5+m', 0.01075713311978963),
 ('C4.5+m', 'C4.5', 0.01075713311978963),
 ('C4.5', 'C4.5+m+cf', 0.015906444101703374),
 ('C4.5+m+cf', 'C4.5', 0.015906444101703374),
 ('C4.5+cf', 'C4.5+m+cf', 0.022909099354356588),
 ('C4.5+m+cf', 'C4.5+cf', 0.022909099354356588),
 ('C4.5+m', 'C4.5+cf', 0.046332729793395394),
 ('C4.5+cf', 'C4.5+m', 0.046332729793395394),
 ('C4.5+m', 'C4.5+m+cf', 0.3278256758446406),
 ('C4.5+m+cf', 'C4.5+m', 0.3278256758446406),
 ('C4.5', 'C4.5+cf', 0.861262330095348),
 ('C4.5+cf', 'C4.5', 0.861262330095348)]

In [18]:
data['C4.5']

0     0.763
1     0.599
2     0.954
3     0.628
4     0.882
5     0.936
6     0.661
7     0.583
8     0.775
9     1.000
10    0.940
11    0.619
12    0.972
13    0.957
Name: C4.5, dtype: float64

In [20]:
data['C4.5+m']

0     0.768
1     0.591
2     0.971
3     0.661
4     0.888
5     0.931
6     0.668
7     0.583
8     0.838
9     1.000
10    0.962
11    0.666
12    0.981
13    0.978
Name: C4.5+m, dtype: float64

In [21]:
from statsmodels.sandbox.stats.multicomp import multipletests

In [22]:
anses = [x for i, x in enumerate(anses) if i % 2 == 0]

In [23]:
anses

[('C4.5', 'C4.5+m', 0.01075713311978963),
 ('C4.5', 'C4.5+m+cf', 0.015906444101703374),
 ('C4.5+m', 'C4.5+cf', 0.046332729793395394),
 ('C4.5+cf', 'C4.5', 0.861262330095348),
 ('C4.5+cf', 'C4.5+m+cf', 0.022909099354356588),
 ('C4.5+m+cf', 'C4.5+m', 0.3278256758446406)]

In [24]:
reject, p_corrected, _, __ = multipletests([x[2] for x in anses], alpha=0.05, method='holm')

In [25]:
reject

array([False, False, False, False, False, False])

In [26]:
p_corrected

array([0.0645428 , 0.07953222, 0.13899819, 0.86126233, 0.0916364 ,
       0.65565135])

In [27]:
reject, p_corrected, _, __ = multipletests([x[2] for x in anses], alpha=0.05, method='fdr_bh')

In [28]:
reject

array([ True,  True, False, False,  True, False])

In [29]:
p_corrected

array([0.0458182 , 0.0458182 , 0.06949909, 0.86126233, 0.0458182 ,
       0.39339081])